"""Uniform interface for learnable tensor-inpainting models."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, Sequence, Tuple

import torch
from torch import nn


class BaseTensorInpaintingModel(nn.Module, ABC):
    """Base class consumed by the fixed Trainer.

    Subclasses parameterize a complete image and expose no image input in
    ``forward``. This is deliberate: all image information reaches optimization
    through the masked loss controlled by the Trainer.
    """

    def __init__(
        self,
        image_shape: Tuple[int, int, int],
        initial_channel_mean: Sequence[float],
    ) -> None:
        super().__init__()
        if len(image_shape) != 3 or image_shape[2] != 3:
            raise ValueError("image_shape must be (height, width, 3)")
        if min(image_shape) < 1:
            raise ValueError("all image dimensions must be positive")
        if len(initial_channel_mean) != image_shape[2]:
            raise ValueError("initial_channel_mean must contain one value per channel")

        self.image_shape = tuple(int(value) for value in image_shape)
        channel_mean = torch.as_tensor(initial_channel_mean, dtype=torch.float32)
        self.channel_bias = nn.Parameter(channel_mean.reshape(1, 1, -1).clone())

    @abstractmethod
    def forward(self) -> torch.Tensor:
        """Return an unconstrained reconstruction with shape [H, W, C]."""

    def regularization_terms(self) -> Dict[str, torch.Tensor]:
        """Return optional differentiable regularizers.

        Day 2 base models intentionally return no regularization. Candidate
        models generated by the Agent may override this method later.
        """

        return {}

    def loss_terms(
        self,
        prediction: torch.Tensor,
        observed: torch.Tensor,
        train_mask: torch.Tensor,
    ) -> Dict[str, torch.Tensor]:
        """Calculate data loss only on training-observed pixels."""

        if tuple(prediction.shape) != self.image_shape:
            raise ValueError("prediction shape does not match model image_shape")
        if observed.shape != prediction.shape:
            raise ValueError("observed image shape must match prediction")
        if train_mask.shape != prediction.shape[:2] or train_mask.dtype != torch.bool:
            raise ValueError("train_mask must be bool with shape [H, W]")
        if not bool(train_mask.any()):
            raise ValueError("train_mask must contain at least one training pixel")

        expanded_mask = train_mask.unsqueeze(-1).expand_as(prediction)
        data_loss = torch.square(prediction - observed)[expanded_mask].mean()
        terms = {"data_loss": data_loss}
        terms.update(self.regularization_terms())
        return terms

    @classmethod
    @abstractmethod
    def search_space(cls, image_shape: Tuple[int, int, int]) -> Dict[str, Any]:
        """Declare tunable hyperparameters for a given image shape."""

