"""Uniform interface for learnable tensor-inpainting models."""

from __future__ import annotations

import math
from abc import ABC, abstractmethod
from typing import Any, Dict, Sequence, Tuple

import torch
from torch import nn


class BaseTensorInpaintingModel(nn.Module, ABC):
    """Base class consumed by the fixed Trainer.

    Subclasses parameterize complete HWC/HWTC data and expose no data input in
    ``forward``. This is deliberate: all observed information reaches optimization
    through the masked loss controlled by the Trainer.
    """

    def __init__(
        self,
        image_shape: Tuple[int, ...],
        initial_channel_mean: Sequence[float],
    ) -> None:
        super().__init__()
        if len(image_shape) not in (3, 4):
            raise ValueError("image_shape must be [H,W,C] or [H,W,T,C]")
        if min(image_shape) < 1:
            raise ValueError("all image dimensions must be positive")
        self.image_shape = tuple(int(value) for value in image_shape)
        self.feature_shape = self.image_shape[2:]
        self.feature_count = int(math.prod(self.feature_shape))
        channel_mean = torch.as_tensor(initial_channel_mean, dtype=torch.float32).reshape(-1)
        if channel_mean.numel() != self.feature_count:
            raise ValueError("initial_channel_mean must contain one value per trailing feature")
        self.channel_bias = nn.Parameter(channel_mean.reshape(1, 1, -1).clone())

    def _restore_shape(self, flattened: torch.Tensor) -> torch.Tensor:
        expected = (self.image_shape[0], self.image_shape[1], self.feature_count)
        if tuple(flattened.shape) != expected:
            raise ValueError("flattened reconstruction shape does not match image_shape")
        return flattened.reshape(self.image_shape)

    @abstractmethod
    def forward(self) -> torch.Tensor:
        """Return an unconstrained reconstruction with shape HWC or HWTC."""

    def regularization_terms(self) -> Dict[str, torch.Tensor]:
        """Return optional differentiable regularizers.

        Day 2 base models intentionally return no regularization. Candidate
        models generated by the Agent may override this method later.
        """

        return {}

    def loss_terms(
        self,
        prediction: torch.Tensor,
        observed: torch.Tensor,
        train_mask: torch.Tensor,
    ) -> Dict[str, torch.Tensor]:
        """Calculate data loss only on training-observed pixels."""

        if tuple(prediction.shape) != self.image_shape:
            raise ValueError("prediction shape does not match model image_shape")
        if observed.shape != prediction.shape:
            raise ValueError("observed image shape must match prediction")
        if train_mask.shape != prediction.shape[:2] or train_mask.dtype != torch.bool:
            raise ValueError("train_mask must be bool with shape [H, W]")
        if not bool(train_mask.any()):
            raise ValueError("train_mask must contain at least one training pixel")

        expanded_mask = train_mask[(...,) + (None,) * (prediction.ndim - 2)].expand_as(
            prediction
        )
        data_loss = torch.square(prediction - observed)[expanded_mask].mean()
        terms = {"data_loss": data_loss}
        terms.update(self.regularization_terms())
        return terms

    @classmethod
    @abstractmethod
    def search_space(cls, image_shape: Tuple[int, ...]) -> Dict[str, Any]:
        """Declare tunable hyperparameters for a given image shape."""
